// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"kratos-ota/internal/biz"
	"kratos-ota/internal/conf"
	"kratos-ota/internal/data"
	"kratos-ota/internal/server"
	"kratos-ota/internal/service"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, auth *conf.Auth, logger log.Logger) (*kratos.App, func(), error) {
	db := data.NewDB(confData, logger)
	dataData, cleanup, err := data.NewData(confData, logger, db)
	if err != nil {
		return nil, nil, err
	}
	roomTypeRepo := data.NewRoomTypeRepo(dataData, logger)
	calendarRepo := data.NewCalendarRepo(dataData, logger)
	otaUsecase := biz.NewOtaUsecase(roomTypeRepo, calendarRepo, auth, logger)
	otaService := service.NewOtaService(otaUsecase)
	httpServer := server.NewHTTPServer(confServer, auth, otaService, logger)
	grpcServer := server.NewGRPCServer(confServer, otaService, logger)
	app := newApp(logger, httpServer, grpcServer)
	return app, func() {
		cleanup()
	}, nil
}
